---
  # TODO: use variables when adequate, setup service with ansible template module if needed, use conditional to avoid unnecessary operations
- hosts: raspberry
  remote_user: pi
  tasks:
  - name: Stop miam service
    become: true
    become_method: sudo
    service:
      name: miam
      state: stopped
  - name: Upload and replace configuration file
    copy:
      src: /miam/deploy/configuration.json
      dest: /home/pi/miam/configuration.json
  - name: Upload and replace executable
    copy:
      src: /miam/main
      dest: /home/pi/miam/main
  - name: Start miam service
    become: true
    become_method: sudo
    service:
      name: miam
      state: started

# TODO: finish to add tasks to setup the service
# scp miam.service pi@192.168.1.21:/tmp/miam.service
# ssh pi@192.168.1.21
# sudo cp /tmp/miam.service /etc/systemd/system/miam.service
# sudo chown root:root /etc/systemd/system/miam.service
# sudo chmod 755 /etc/systemd/system/miam.service
# sudo systemctl daemon-reload
# sudo systemctl start miam
# sudo systemctl enable miam
